trigger:
- main
pr:
- main

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - checkout: self
    fetchDepth: '0'
  - pwsh: |
      npm install
      npm run format-check
      npm run build:azure
    displayName: 'Build code'
